# Stubs for delira.backends (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List

__POSSIBLE_BACKENDS: Any
__BACKENDS: Any

def _determine_backends() -> None: ...
def get_backends() -> List[str]: ...
def seed_all(seed: int) -> None: ...
