# Stubs for delira.data_loading.numba_transform (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import numpy as np
from batchgenerators.transforms import AbstractTransform, Compose
from typing import Any, Dict, Iterable, List, Type, Union

logger: Any

class NumbaTransformWrapper(AbstractTransform):
    _transform: Any = ...
    def __init__(self, transform: AbstractTransform, nopython: bool=..., target: str=..., parallel: bool=..., **options: Any) -> Any: ...
    def __call__(self, **kwargs: Any) -> Dict[str, np.ndarray]: ...

class NumbaTransform(NumbaTransformWrapper):
    def __init__(self, transform_cls: Type[AbstractTransform], nopython: bool=..., target: str=..., parallel: bool=..., **kwargs: Any) -> Any: ...

class NumbaCompose(Compose):
    def __init__(self, transforms: Union[List, Iterable]) -> Any: ...
