# Stubs for delira.utils.config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from trixi.util import Config
from typing import Any

class LookupConfig(Config):
    def nested_get(self, key: str, *args: Any, **kwargs: Any) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
