# Stubs for delira.utils.decorators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Callable, Type, Union

def dtype_func(class_object: Type[Any]) -> Callable: ...
def classtype_func(class_object: Any) -> Callable: ...
def make_deprecated(new_func: Union[str, Callable]) -> Callable: ...

numpy_array_func: Any
torch_tensor_func: Any
torch_module_func: Any
