# Stubs for delira.utils.path (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Iterable, List, Tuple, Union

def subdirs(d: str) -> Union[List[str], Tuple[str], Iterable[str]]: ...
